SELECT TO_CHAR(OS.SALES_DATE, 'YYYY') AS YEAR
, TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM')) AS MONTH
, COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS
, ROUND(COUNT(DISTINCT OS.USER_ID)/(SELECT COUNT(T1.USER_ID) FROM USER_INFO T1 WHERE TO_CHAR(JOINED, 'YYYY') = '2021'),1) AS PUCHASED_RATIO
FROM USER_INFO UI
LEFT JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
AND TO_CHAR(UI.JOINED, 'YYYY') = '2021'
WHERE SALES_DATE IS NOT NULL
GROUP BY TO_CHAR(OS.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM'))
ORDER BY YEAR, MONTH
