SELECT  FP.PRODUCT_ID
,       FP.PRODUCT_NAME
,       SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO
ON FO.PRODUCT_ID = FP.PRODUCT_ID
AND TO_CHAR(FO.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID